apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
  namespace: quiz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
      - name: frontend
        image: ajithrock/project1-frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend
  namespace: quiz
spec:
  type: NodePort
  selector:
    app: quiz-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080